12-react/secrets_server/config/routes.rb
Rails.application.routes.draw do
  resources :secrets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

12-react/secrets_server/app/models/secret.rb
class Secret < ApplicationRecord
end

12-react/secrets_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token # This is required for APIs.
end

12-react/secrets_server/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :set_secret, only: [:show, :edit, :update, :destroy]

  # GET /secrets
  # GET /secrets.json
  def index
    @secrets = Secret.all
  end

  # GET /secrets/1
  # GET /secrets/1.json
  def show
  end

  # GET /secrets/new
  def new
    @secret = Secret.new
  end

  # GET /secrets/1/edit
  def edit
  end

  # POST /secrets
  # POST /secrets.json
  def create
    @secret = Secret.new(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to @secret, notice: 'Secret was successfully created.' }
        format.json { render :show, status: :created, location: @secret }
      else
        format.html { render :new }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secrets/1
  # PATCH/PUT /secrets/1.json
  def update
    respond_to do |format|
      if @secret.update(secret_params)
        format.html { redirect_to @secret, notice: 'Secret was successfully updated.' }
        format.json { render :show, status: :ok, location: @secret }
      else
        format.html { render :edit }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secrets/1
  # DELETE /secrets/1.json
  def destroy
    @secret.destroy
    respond_to do |format|
      format.html { redirect_to secrets_url, notice: 'Secret was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_params
      params.require(:secret).permit(:content)
    end
end

12-react/secrets_server/app/helpers/secrets_helper.rb
module SecretsHelper
end

12-react/secrets_server/app/views/secrets/_form.html.erb
<%= form_with(model: secret, local: true) do |form| %>
  <% if secret.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secret.errors.count, "error") %> prohibited this secret from being saved:</h2>

      <ul>
      <% secret.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

12-react/secrets_server/app/views/secrets/edit.html.erb
<h1>Editing Secret</h1>

<%= render 'form', secret: @secret %>

<%= link_to 'Show', @secret %> |
<%= link_to 'Back', secrets_path %>

12-react/secrets_server/app/views/secrets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Secrets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secrets.each do |secret| %>
      <tr>
        <td><%= secret.content %></td>
        <td><%= link_to 'Show', secret %></td>
        <td><%= link_to 'Edit', edit_secret_path(secret) %></td>
        <td><%= link_to 'Destroy', secret, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secret', new_secret_path %>

12-react/secrets_server/app/views/secrets/new.html.erb
<h1>New Secret</h1>

<%= render 'form', secret: @secret %>

<%= link_to 'Back', secrets_path %>

12-react/secrets_server/app/views/secrets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @secret.content %>
</p>

<%= link_to 'Edit', edit_secret_path(@secret) %> |
<%= link_to 'Back', secrets_path %>