08-rails/view_helpers/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get '/numb3rs' => 'pages#numbers', :as => :numbers
  get '/text' => 'pages#text'
  get '/assets' => 'pages#assets'
  get '/url' => 'pages#url'
end

08-rails/view_helpers/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def numbers
    @amount = 232938.28743
    @large_number = 239343498
    @phone = 2125551212
  end

  def text
    @numbers = (1..20).to_a.shuffle
    @friend_count = 1
    @enemy_count = 11
    @story = "A very very very very very very very very long time ago in a galaxy far far far far far far far far away."
  end

  def assets
  end

  def url
  end
end

08-rails/view_helpers/app/views/pages/assets.html.erb
<h2>Asset Helpers</h2>

<!-- <img src="http://www.placecage.com/300/300" alt="Scary Nicholas Cage"> -->

<%= image_tag "http://www.placecage.com/300/300", :alt => 'Nic' %>

<!-- <img src="/assets/smoking.jpg" alt="Kids lighting up"> -->

<%= image_tag "smoking.jpg", :alt => 'Kids lighting up', :class => 'kids' %>

<p>There is also: video_tag, audio_tag</p>

08-rails/view_helpers/app/views/pages/home.html.erb
<h1>View Helpers Demo</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam omnis architecto porro distinctio, obcaecati suscipit corrupti iusto earum eos laboriosam aspernatur, perferendis eligendi asperiores beatae accusamus vero sapiente dolorum quae.</p>

08-rails/view_helpers/app/views/pages/numbers.html.erb
<h2>Number Helpers</h2>
<p><%= number_to_currency @amount %></p>
<p title="<%= @large_number %>"><%= number_to_human @large_number %></p>
<p><%= number_to_phone @phone, :area_code => true %></p>

08-rails/view_helpers/app/views/pages/text.html.erb
<h2>Text Helpers</h2>
<ul>
  <% @numbers.each do |n| %>
    <li style="background-color: <%= cycle('red', 'green', 'orange', 'purple') %>"><%= n %></li>
  <% end %>
</ul>

<p><%= truncate @story, :length => 30 %></p>

<p><%= pluralize @friend_count, 'friend' %>.</p>
<p><%= pluralize @enemy_count, 'enemy' %>.</p>

08-rails/view_helpers/app/views/pages/url.html.erb
<h2>URL Helpers</h2>

<h3>Hard coding URLs is a bad idea</h3>

<a href="/numbers">Number helpers</a>

<%= link_to "Number helpers", numbers_path %>